// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyiqszblaypkdkjrurzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5aXFzemJsYXlwa2RranJ1cnpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMDQ1MDYsImV4cCI6MjA2Mjg4MDUwNn0.jo_tMH_XncWb7iwIPBqJ3Y73MUUs9JzEHnWoagFbSmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);